//
//  PlayGameConstants.h
//  GooglePlayGameServices
//
//  Created by NSS on 4/7/14.
//
//

#ifndef GooglePlayGameServices_PlayGameConstants_h
#define GooglePlayGameServices_PlayGameConstants_h

#define CLIENT_ID "893066960841-cgr2uksjuhjsihksn7khog52275o97qd.apps.googleusercontent.com"
#define GPGApplicationID "893066960841"

#define ACH_FIRST_TIME_PLAYING_THE_GAME "CgkIyb_B9_4ZEAIQFA"
#define ACH_MORE_THAN_3000 "CgkIyb_B9_4ZEAIQBQ"
#define ACH_PLAY_10_TIMES "CgkIyb_B9_4ZEAIQCg"
#define ACH_PLAY_100_TIMES "CgkIyb_B9_4ZEAIQCQ"
#define ACH_PLAY_1000_TIMES "CgkIyb_B9_4ZEAIQCw"
#define ACH_AVOID_25_OBSTACLES_IN_HARD_MODE "CgkIyb_B9_4ZEAIQBg"
#define ACH_AVOID_50_OBSTACLES_IN_NORMAL_MODE "CgkIyb_B9_4ZEAIQBw"
#define ACH_AVOID_100_OBSTACLES_IN_EASY_MODE "CgkIyb_B9_4ZEAIQCA"
#define ACH_JUMP_50_OBSTACLES "CgkIyb_B9_4ZEAIQDA"
#define ACH_GET_10000_OR_MORE_IN_EASY_MODE "CgkIyb_B9_4ZEAIQDQ"
#define ACH_GET_8000_OR_MORE_IN_NORMAL_MODE "CgkIyb_B9_4ZEAIQDg"
#define ACH_GET_5000_OR_MORE_IN_HARD_MODE "CgkIyb_B9_4ZEAIQDw"
#define ACH_AVERAGE_1000_OR_MORE_IN_50_GAMES_OR_MORE "CgkIyb_B9_4ZEAIQEA"
#define ACH_GET_TOTAL_SCORE_100000_OR_MORE "CgkIyb_B9_4ZEAIQEQ"
#define ACH_PLAY_IN_ACCELEROMETER_MODE "CgkIyb_B9_4ZEAIQEg"
#define ACH_PLAY_IN_ACCELEROMETER_MODE_AND_GET_MORE_THAN_3000 "CgkIyb_B9_4ZEAIQEw"
#define ACH_JUMP_1000_OBSTACLES "CgkIyb_B9_4ZEAIQFg"
#define ACH_AVOID_100_OBSTACLES_IN_HARD_MODE "CgkIyb_B9_4ZEAIQFw"

#define LEAD_EASY_MODE "CgkIyb_B9_4ZEAIQAg"
#define LEAD_NORMAL_MODE "CgkIyb_B9_4ZEAIQAw"
#define LEAD_HARD_MODE "CgkIyb_B9_4ZEAIQBA"



#endif
