//
//  PlayGameConstants.h
//  GooglePlayGameServices
//
//  Created by NSS on 4/7/14.
//
//

#ifndef GooglePlayGameServices_PlayGameConstants_h
#define GooglePlayGameServices_PlayGameConstants_h

#include "cocos2d.h"

#define IOS() (CC_TARGET_PLATFORM == CC_PLATFORM_IOS)

#define ACH_MORE_THAN_3000 !IOS() ? "CgkIyb_B9_4ZEAIQBQ" : "ACH_MORE_THAN_3000"

#define ACH_PLAY_10_TIMES !IOS() ? "CgkIyb_B9_4ZEAIQCg" : "ACH_PLAY_10_TIMES"

#define ACH_PLAY_100_TIMES !IOS() ? "CgkIyb_B9_4ZEAIQCQ" : "ACH_PLAY_100_TIMES"

#define ACH_PLAY_1000_TIMES !IOS() ? "CgkIyb_B9_4ZEAIQCw" : "ACH_PLAY_1000_TIMES"

#define ACH_AVOID_25_OBSTACLES_IN_HARD_MODE !IOS() ? "CgkIyb_B9_4ZEAIQBg" : "ACH_AVOID_25_OBSTACLES_IN_HARD_MODE"

#define ACH_AVOID_50_OBSTACLES_IN_NORMAL_MODE !IOS() ? "CgkIyb_B9_4ZEAIQBw" : "ACH_AVOID_50_OBSTACLES_IN_NORMAL_MODE"

#define ACH_AVOID_100_OBSTACLES_IN_EASY_MODE !IOS() ? "CgkIyb_B9_4ZEAIQCA" : "ACH_AVOID_100_OBSTACLES_IN_EASY_MODE"

#define ACH_JUMP_50_OBSTACLES !IOS() ? "CgkIyb_B9_4ZEAIQDA" : "ACH_JUMP_50_OBSTACLES"

#define ACH_GET_10000_OR_MORE_IN_EASY_MODE !IOS() ? "CgkIyb_B9_4ZEAIQDQ" : "ACH_GET_10000_OR_MORE_IN_EASY_MODE"

#define ACH_GET_8000_OR_MORE_IN_NORMAL_MODE !IOS() ? "CgkIyb_B9_4ZEAIQDg" : "ACH_GET_8000_OR_MORE_IN_NORMAL_MODE"

#define ACH_GET_5000_OR_MORE_IN_HARD_MODE !IOS() ? "CgkIyb_B9_4ZEAIQDw" : "ACH_GET_5000_OR_MORE_IN_HARD_MODE"

#define ACH_AVERAGE_1000_OR_MORE_IN_50_GAMES_OR_MORE !IOS() ? "CgkIyb_B9_4ZEAIQEA" : "ACH_AVERAGE_1000_OR_MORE_IN_50_GAMES_OR_MORE"

#define ACH_GET_TOTAL_SCORE_100000_OR_MORE !IOS() ? "CgkIyb_B9_4ZEAIQEQ" : "ACH_GET_TOTAL_SCORE_100000_OR_MORE"

#define ACH_PLAY_IN_ACCELEROMETER_MODE !IOS() ? "CgkIyb_B9_4ZEAIQEg" : "ACH_PLAY_IN_ACCELEROMETER_MODE"

#define ACH_PLAY_IN_ACCELEROMETER_MODE_AND_GET_MORE_THAN_3000 !IOS() ? "CgkIyb_B9_4ZEAIQEw" : "ACH_PLAY_IN_ACCELEROMETER_MODE_AND_GET_MORE_THAN_3000"

#define ACH_JUMP_1000_OBSTACLES !IOS() ? "CgkIyb_B9_4ZEAIQFg" : "ACH_JUMP_1000_OBSTACLES"

#define ACH_AVOID_100_OBSTACLES_IN_HARD_MODE !IOS() ? "CgkIyb_B9_4ZEAIQFw" : "ACH_AVOID_100_OBSTACLES_IN_HARD_MODE"

#define ACH_GET_30K_IN_EASY_MODE "CgkIyb_B9_4ZEAIQGw"
#define ACH_GET_15K_IN_NORMAL_MODE "CgkIyb_B9_4ZEAIQHA"
#define ACH_GET_10K_IN_HARD_MODE "CgkIyb_B9_4ZEAIQHQ"


#define LEAD_EASY_MODE !IOS() ? "CgkIyb_B9_4ZEAIQAg" : "LEAD_EASY_MODE"

#define LEAD_NORMAL_MODE !IOS() ? "CgkIyb_B9_4ZEAIQAw" : "LEAD_NORMAL_MODE"

#define LEAD_HARD_MODE !IOS() ? "CgkIyb_B9_4ZEAIQBA" : "LEAD_HARD_MODE"

#endif
